version: '3.9'

services:

  postgres:
    container_name: flaskblog-postgres
    image: postgres:16.1
    restart: on-failure
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}
    ports:
      - ${PG_PORT}:${PG_PORT}
    expose:
      - ${PG_PORT}
    networks:
      - custom

  redis:
    container_name: flaskblog-redis
    image: redis:7.2.3
    restart: on-failure
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    networks:
      - custom

  web:
    container_name: flaskblog-web
    build: .
    command: "sh -c 'set FLASK_APP=wsgi.py && flask db upgrade && gunicorn -c gunicorn.conf.py wsgi:app'"
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    depends_on:
      - postgres
      - redis
    networks:
      - custom

  worker:
    container_name: flaskblog-celery
    build: .
    command: "sh -c 'celery -A wsgi.celery_app worker --loglevel WARNING'"
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - web
    networks:
      - custom


networks:

  custom:
    driver: bridge