"""Initial

Revision ID: c346fb101cfd
Revises:
Create Date: 2024-02-24 20:19:22.816412

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c346fb101cfd"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("picture", sa.String(), server_default="/static/img/userimg/default.jpg", nullable=False),
        sa.Column(
            "status",
            sa.Enum("default", "author", "admin", name="userstatus"),
            server_default="default",
            nullable=False,
        ),
        sa.Column("fullname", sa.String(), nullable=True),
        sa.Column("job_title", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("github", sa.String(), nullable=True),
        sa.Column("twitter", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_user_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "post",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("intro", sa.String(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("picture", sa.String(), nullable=False),
        sa.Column("group", sa.Enum("articles", "news", name="postgroup"), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "development",
                "administration",
                "design",
                "management",
                "marketing",
                "science",
                name="postcategory",
            ),
            nullable=False,
        ),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_post_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_post_slug"), ["slug"], unique=True)
        batch_op.create_index(batch_op.f("ix_post_title"), ["title"], unique=True)

    op.create_table(
        "comment",
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("post_id", sa.Uuid(), nullable=False),
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_comment_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("comment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comment_id"))

    op.drop_table("comment")
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_post_title"))
        batch_op.drop_index(batch_op.f("ix_post_slug"))
        batch_op.drop_index(batch_op.f("ix_post_id"))

    op.drop_table("post")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))
        batch_op.drop_index(batch_op.f("ix_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    # ### end Alembic commands ###
